package cn.fh.codeschool.model;
// Generated Apr 29, 2014 2:35:49 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MemberRoleId generated by hbm2java
 */
@Embeddable
public class MemberRoleId implements java.io.Serializable {

	private int memberId;
	private int roleId;

	public MemberRoleId() {
	}

	public MemberRoleId(int memberId, int roleId) {
		this.memberId = memberId;
		this.roleId = roleId;
	}

	@Column(name = "member_id", unique = false, nullable = false)
	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	@Column(name = "role_id", unique = false, nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MemberRoleId))
			return false;
		MemberRoleId castOther = (MemberRoleId) other;

		return (this.getMemberId() == castOther.getMemberId())
				&& (this.getRoleId() == castOther.getRoleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMemberId();
		result = 37 * result + this.getRoleId();
		return result;
	}

}
