package cn.fh.codeschool.model;
// Generated Apr 29, 2014 2:35:49 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Size;

/**
 * Role generated by hbm2java
 */

@NamedQuery(
		name = "Role.fetchAllRoles",
		query = "select r from Role r"
		)

@Entity
@Table(name = "role", schema = "public")
public class Role implements java.io.Serializable {

	private int id;
	private String roleName;
	private String memo;
	private Set<MemberRole> memberRoles = new HashSet<MemberRole>(0);

	public Role() {
	}

	public Role(int id) {
		this.id = id;
	}
	public Role(int id, String roleName, String memo,
			Set<MemberRole> memberRoles) {
		this.id = id;
		this.roleName = roleName;
		this.memo = memo;
		this.memberRoles = memberRoles;
	}

	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "role_name", length = 64)
	@Size(max = 64)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "memo")
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<MemberRole> getMemberRoles() {
		return this.memberRoles;
	}

	public void setMemberRoles(Set<MemberRole> memberRoles) {
		this.memberRoles = memberRoles;
	}

}
